version: '3'
services:
  redis:
    image: redis
    container_name: redis
    networks:
      - default
    volumes:
      - cache:/data
    ports:
      - 6379:6379
    expose:
      - 6379
    restart: unless-stopped
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    env_file:
      - redis.env

volumes:
  cache:

networks:
  default:
    name: common
